name = "TGCSMP"
author = "Mirraaa"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04b2d647b0cc130ede023c1385a58dd3f21f65aaef78cf9d90c4d89fcc0f7ff1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
