name = "TrinitySMP"
author = "Mirraaa"
version = "1.0.16"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be8eeada32a06f6baca23faa0a168bc5e18b257bb35c69c8e7489ef2d4fa1d8d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
