name = "TrinitySMP"
author = "Mirraaa"
version = "1.0.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "796783574e7a922f13b4a9c3d288b0189e3aa0c337616d71ed918a9a35204d09"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
